extends RefCounted

var host


func _init(check_host) -> void:
	host = check_host


func run_flow(world_state: WorldState, character_state: CharacterState) -> void:
	host._expect_active_quest("quest.analyze_phase_well_heart", "after phase well sink returns to heart analysis")
	host._complete_active_quest("quest.analyze_phase_well_heart", [{"type": "craft_item", "target_id": "item.phase_well_pulse_sheet", "amount": 1}])
	host._expect_active_quest("quest.collect_heart_spine", "after heart analysis returns to chamber edge")
	host._expect_array_has(world_state.unlocked_region_ids, "region.phase_well_chamber", "phase well heart analysis unlocks phase well chamber region")
	host._complete_active_quest("quest.collect_heart_spine", [
		{"type": "visit_region", "target_id": "region.phase_well_chamber", "amount": 1},
		{"type": "defeat_enemy", "target_id": "enemy.phase_well_reaver", "amount": 1},
		{"type": "gather_item", "target_id": "item.heart_spine", "amount": 2}
	])
	host._expect_active_quest("quest.refine_heart_spine", "after heart spine collection returns to filter")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "recipe.heart_spine_stabilization", "heart spine collection unlocks stabilization recipe")
	host._complete_active_quest("quest.refine_heart_spine", [{"type": "craft_item", "target_id": "item.phase_well_damper", "amount": 1}])
	host._expect_active_quest("quest.assemble_phase_well_shunt", "after heart spine refinement returns to reactor")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "recipe.phase_well_shunt", "heart spine refinement unlocks phase well shunt recipe")
	host._complete_active_quest("quest.assemble_phase_well_shunt", [{"type": "craft_item", "target_id": "item.phase_well_shunt", "amount": 1}])
	host._expect_active_quest("quest.inspect_phase_well_chamber", "after phase well shunt assembly returns to chamber")
	host._complete_active_quest("quest.inspect_phase_well_chamber", [{"type": "inspect", "target_id": "map_object.phase_well_chamber", "amount": 1}])
	host._expect_active_quest("quest.analyze_phase_well_spindle", "after phase well chamber returns to spindle analysis")
	host._expect_array_has(world_state.quest_state.completed_quest_ids, "quest.inspect_phase_well_chamber", "phase well chamber quest completed")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "recipe.phase_well_spindle_analysis", "phase well chamber unlocks spindle analysis recipe")
	host._expect_equal(int(character_state.inventory.items.get("item.phase_well_spindle", 0)), 1, "phase well chamber grants first spindle reward")
	host._complete_active_quest("quest.analyze_phase_well_spindle", [{"type": "craft_item", "target_id": "item.phase_well_warp_sheet", "amount": 1}])
	host._expect_active_quest("quest.collect_weft_bundle", "after spindle analysis returns to loom edge")
	host._expect_array_has(world_state.unlocked_region_ids, "region.phase_well_loom", "phase well spindle analysis unlocks phase well loom region")
	host._complete_active_quest("quest.collect_weft_bundle", [
		{"type": "visit_region", "target_id": "region.phase_well_loom", "amount": 1},
		{"type": "defeat_enemy", "target_id": "enemy.phase_well_tangler", "amount": 1},
		{"type": "gather_item", "target_id": "item.weft_bundle", "amount": 2}
	])
	host._expect_active_quest("quest.refine_weft_bundle", "after weft bundle collection returns to filter")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "recipe.weft_bundle_stabilization", "weft bundle collection unlocks stabilization recipe")
	host._complete_active_quest("quest.refine_weft_bundle", [{"type": "craft_item", "target_id": "item.phase_well_tension_rib", "amount": 1}])
	host._expect_active_quest("quest.assemble_phase_well_shuttle", "after weft bundle refinement returns to reactor")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "recipe.phase_well_shuttle", "weft bundle refinement unlocks phase well shuttle recipe")
	host._complete_active_quest("quest.assemble_phase_well_shuttle", [{"type": "craft_item", "target_id": "item.phase_well_shuttle", "amount": 1}])
	host._expect_active_quest("quest.inspect_phase_well_loom", "after phase well shuttle assembly returns to loom")
	host._complete_active_quest("quest.inspect_phase_well_loom", [{"type": "inspect", "target_id": "map_object.phase_well_loom", "amount": 1}])
	host._expect_array_has(world_state.quest_state.completed_quest_ids, "quest.inspect_phase_well_loom", "phase well loom quest completed")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "slice_01_complete", "phase well loom restores terminal slice completion unlock")
	host._expect_equal(int(character_state.inventory.items.get("item.phase_well_weave_core", 0)), 1, "phase well loom grants first weave core reward")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "recipe.phase_well_weave_core_analysis", "phase well loom unlocks weave core analysis recipe")
	host._expect_active_quest("quest.analyze_phase_well_weave_core", "after phase well loom returns to weave core analysis")
	host._complete_active_quest("quest.analyze_phase_well_weave_core", [{"type": "craft_item", "target_id": "item.phase_well_pattern_sheet", "amount": 1}])
	host._expect_active_quest("quest.collect_selvedge_strip", "after weave core analysis returns to frame edge")
	host._expect_array_has(world_state.unlocked_region_ids, "region.phase_well_frame", "phase well weave core analysis unlocks phase well frame region")
	host._complete_active_quest("quest.collect_selvedge_strip", [
		{"type": "visit_region", "target_id": "region.phase_well_frame", "amount": 1},
		{"type": "defeat_enemy", "target_id": "enemy.phase_well_raker", "amount": 1},
		{"type": "gather_item", "target_id": "item.selvedge_strip", "amount": 2}
	])
	host._expect_active_quest("quest.refine_selvedge_strip", "after selvedge strip collection returns to filter")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "recipe.selvedge_strip_stabilization", "selvedge strip collection unlocks stabilization recipe")
	host._complete_active_quest("quest.refine_selvedge_strip", [{"type": "craft_item", "target_id": "item.phase_well_frame_rib", "amount": 1}])
	host._expect_active_quest("quest.assemble_phase_well_frame_key", "after selvedge strip refinement returns to reactor")
	host._expect_array_has(world_state.quest_state.unlocked_effects, "recipe.phase_well_frame_key", "selvedge strip refinement unlocks phase well frame key recipe")
	host._complete_active_quest("quest.assemble_phase_well_frame_key", [{"type": "craft_item", "target_id": "item.phase_well_frame_key", "amount": 1}])
	host._expect_active_quest("quest.inspect_phase_well_frame", "after phase well frame key assembly returns to frame")
	host._complete_active_quest("quest.inspect_phase_well_frame", [{"type": "inspect", "target_id": "map_object.phase_well_frame", "amount": 1}])
	host._expect_equal(world_state.quest_state.active_quest_ids, [], "after phase well frame should have no active quest")
	host._expect_array_has(world_state.quest_state.completed_quest_ids, "quest.inspect_phase_well_frame", "phase well frame quest completed")
	host._expect_equal(int(character_state.inventory.items.get("item.phase_well_knot_core", 0)), 1, "phase well frame grants first knot core reward")


func run_hud_and_map_checks() -> void:
	_check_onboarding_hints()
	_check_status_panel_summary()
	_check_region_presence_bounds()
	_check_phase_well_chamber_gate()
	_check_phase_well_loom_gate()
	_check_phase_well_frame_gate()


func _check_onboarding_hints() -> void:
	var presenter := HudHintPresenter.new()
	var hint_world := WorldState.create_default()
	var hint_character := CharacterState.create_default()
	var heart_completion_world := WorldState.create_default()
	heart_completion_world.quest_state.active_quest_ids.clear()
	heart_completion_world.quest_state.completed_quest_ids.append("quest.inspect_phase_well_sink")
	host._expect_text_contains(presenter.format_direction_hint(heart_completion_world, hint_character, ""), "回基地解析心核", "phase well heart completion direction highlights next base analysis")
	host._expect_text_contains(presenter.format_onboarding_hint(heart_completion_world, hint_character, ""), "相位井心核不是收尾", "phase well heart completion onboarding keeps next package explicit")
	host._expect_hint_contains(presenter, hint_world, hint_character, "quest.analyze_phase_well_heart", "脉搏片", "phase well heart analysis onboarding hint")
	host._expect_hint_contains(presenter, hint_world, hint_character, "quest.assemble_phase_well_shunt", "井心分流栓", "phase well shunt assembly onboarding hint")
	host._expect_hint_contains(presenter, hint_world, hint_character, "quest.analyze_phase_well_spindle", "经片", "phase well spindle analysis onboarding hint")
	host._expect_hint_contains(presenter, hint_world, hint_character, "quest.refine_weft_bundle", "第三台设备", "weft bundle refinement onboarding keeps device reuse explicit")
	host._expect_hint_contains(presenter, hint_world, hint_character, "quest.inspect_phase_well_loom", "井纺梭栓", "phase well loom onboarding hint")
	var chamber_completion_world := WorldState.create_default()
	chamber_completion_world.quest_state.active_quest_ids.clear()
	chamber_completion_world.quest_state.completed_quest_ids.append("quest.inspect_phase_well_chamber")
	host._expect_text_contains(presenter.format_direction_hint(chamber_completion_world, hint_character, ""), "回基地解析纺核", "phase well chamber completion direction points to spindle analysis")
	host._expect_text_contains(presenter.format_onboarding_hint(chamber_completion_world, hint_character, ""), "相位井纺核不是收尾", "phase well chamber completion onboarding keeps loom package explicit")
	var loom_completion_world := WorldState.create_default()
	loom_completion_world.quest_state.active_quest_ids.clear()
	loom_completion_world.quest_state.completed_quest_ids.append("quest.inspect_phase_well_loom")
	host._expect_text_contains(presenter.format_direction_hint(loom_completion_world, hint_character, ""), "回基地解析织核", "phase well loom completion direction points to phase well frame analysis")
	host._expect_text_contains(presenter.format_onboarding_hint(loom_completion_world, hint_character, ""), "相位井织核不是收尾", "phase well loom completion onboarding keeps frame package explicit")
	host._expect_hint_contains(presenter, hint_world, hint_character, "quest.analyze_phase_well_weave_core", "纹谱片", "phase well weave core analysis onboarding hint")
	host._expect_hint_contains(presenter, hint_world, hint_character, "quest.assemble_phase_well_frame_key", "井纹架键栓", "phase well frame key assembly onboarding hint")
	host._expect_hint_contains(presenter, hint_world, hint_character, "quest.inspect_phase_well_frame", "井纹架键栓", "phase well frame onboarding hint")
	var frame_completion_world := WorldState.create_default()
	frame_completion_world.quest_state.active_quest_ids.clear()
	frame_completion_world.quest_state.completed_quest_ids.append("quest.inspect_phase_well_frame")
	host._expect_text_contains(presenter.format_direction_hint(frame_completion_world, hint_character, ""), "相位井结核", "phase well frame completion direction summarizes latest reward anchor")
	host._expect_text_contains(presenter.format_onboarding_hint(frame_completion_world, hint_character, ""), "相位井结核已经带回基地", "phase well frame completion onboarding summarizes latest reward anchor")


func _check_status_panel_summary() -> void:
	var presenter := HudStatusPresenter.new()
	var status_character := CharacterState.create_default()
	var phase_well_sink_text_world := WorldState.create_default()
	phase_well_sink_text_world.quest_state.active_quest_ids.clear()
	phase_well_sink_text_world.quest_state.completed_quest_ids.append("quest.inspect_phase_well_sink")
	var phase_well_sink_text := presenter.format_status_text(host.data_registry, phase_well_sink_text_world, status_character)
	host._expect_text_contains(phase_well_sink_text, "目标：相位井心核待解析", "status falls back to phase well heart analysis after sink")
	host._expect_text_contains(phase_well_sink_text, "回基地解析相位井心核后", "status progress keeps phase well heart followup summary")
	var phase_well_chamber_text_world := WorldState.create_default()
	phase_well_chamber_text_world.quest_state.active_quest_ids.clear()
	phase_well_chamber_text_world.quest_state.completed_quest_ids.append("quest.inspect_phase_well_chamber")
	var phase_well_chamber_text := presenter.format_status_text(host.data_registry, phase_well_chamber_text_world, status_character)
	host._expect_text_contains(phase_well_chamber_text, "目标：相位井纺核待解析", "status falls back to phase well spindle summary after chamber")
	host._expect_text_contains(phase_well_chamber_text, "回基地解析相位井纺核后", "status progress keeps phase well chamber followup summary")
	var phase_well_loom_text_world := WorldState.create_default()
	phase_well_loom_text_world.quest_state.active_quest_ids.clear()
	phase_well_loom_text_world.quest_state.completed_quest_ids.append("quest.inspect_phase_well_loom")
	var phase_well_loom_text := presenter.format_status_text(host.data_registry, phase_well_loom_text_world, status_character)
	host._expect_text_contains(phase_well_loom_text, "目标：相位井织核待解析", "status falls back to phase well weave core analysis after loom")
	host._expect_text_contains(phase_well_loom_text, "回基地解析相位井织核后", "status progress keeps phase well loom followup summary")
	var phase_well_frame_text_world := WorldState.create_default()
	phase_well_frame_text_world.quest_state.active_quest_ids.clear()
	phase_well_frame_text_world.quest_state.completed_quest_ids.append("quest.inspect_phase_well_frame")
	var phase_well_frame_text := presenter.format_status_text(host.data_registry, phase_well_frame_text_world, status_character)
	host._expect_text_contains(phase_well_frame_text, "目标：相位井结核已带回", "status falls back to phase well knot core summary after frame")
	host._expect_text_contains(phase_well_frame_text, "井纹架断面已勘验", "status progress keeps phase well frame summary")


func _check_region_presence_bounds() -> void:
	var map := VerticalSliceMap.new()
	host._expect_equal(map._get_region_id_for_position(Vector2(2282, -18)), "region.phase_well_chamber", "phase well chamber should sit in the eastern chamber region")
	host._expect_equal(map._get_region_id_for_position(Vector2(2562, -18)), "region.phase_well_loom", "phase well loom should sit in the new eastern loom region")
	host._expect_equal(map._get_region_id_for_position(Vector2(2842, -18)), "region.phase_well_frame", "phase well frame should sit in the new eastern frame region")
	map.free()


func _check_phase_well_chamber_gate() -> void:
	var map := VerticalSliceMap.new()
	map.player = PlayerController.new()
	var chamber_gate_world := WorldState.create_default()
	chamber_gate_world.unlock_region("region.crystal_vein_field")
	chamber_gate_world.unlock_region("region.pollution_edge")
	chamber_gate_world.unlock_region("region.ruin_outer_ring")
	chamber_gate_world.unlock_region("region.deep_ruin_threshold")
	chamber_gate_world.unlock_region("region.inner_phase_well")
	chamber_gate_world.unlock_region("region.phase_well_sink")
	chamber_gate_world.quest_state.completed_quest_ids.append("quest.stabilize_outer_ring_barrier")
	chamber_gate_world.quest_state.completed_quest_ids.append("quest.unlock_deep_ruin_entrance")
	var chamber_gate_character := CharacterState.create_default()
	map.last_reported_region_id = chamber_gate_world.current_region_id
	map.player.position = Vector2(2106, -96)
	map.update_region_presence(chamber_gate_world, chamber_gate_character)
	host._expect_equal(map.player.position.x, 2012.0, "locked phase well chamber should push player before chamber region")
	host._expect_equal(chamber_gate_world.current_region_id, "region.phase_well_sink", "locked phase well chamber should keep sink region")
	var unlocked_chamber_world := WorldState.create_default()
	unlocked_chamber_world.unlock_region("region.crystal_vein_field")
	unlocked_chamber_world.unlock_region("region.pollution_edge")
	unlocked_chamber_world.unlock_region("region.ruin_outer_ring")
	unlocked_chamber_world.unlock_region("region.deep_ruin_threshold")
	unlocked_chamber_world.unlock_region("region.inner_phase_well")
	unlocked_chamber_world.unlock_region("region.phase_well_sink")
	unlocked_chamber_world.unlock_region("region.phase_well_chamber")
	unlocked_chamber_world.quest_state.completed_quest_ids.append("quest.stabilize_outer_ring_barrier")
	unlocked_chamber_world.quest_state.completed_quest_ids.append("quest.unlock_deep_ruin_entrance")
	var unlocked_chamber_character := CharacterState.create_default()
	map.last_reported_region_id = unlocked_chamber_world.current_region_id
	map.player.position = Vector2(2106, -96)
	map.update_region_presence(unlocked_chamber_world, unlocked_chamber_character)
	host._expect_equal(unlocked_chamber_world.current_region_id, "region.phase_well_chamber", "unlocked phase well chamber should update current region")
	map.player.free()
	map.free()


func _check_phase_well_loom_gate() -> void:
	var map := VerticalSliceMap.new()
	map.player = PlayerController.new()
	var loom_gate_world := WorldState.create_default()
	loom_gate_world.unlock_region("region.crystal_vein_field")
	loom_gate_world.unlock_region("region.pollution_edge")
	loom_gate_world.unlock_region("region.ruin_outer_ring")
	loom_gate_world.unlock_region("region.deep_ruin_threshold")
	loom_gate_world.unlock_region("region.inner_phase_well")
	loom_gate_world.unlock_region("region.phase_well_sink")
	loom_gate_world.unlock_region("region.phase_well_chamber")
	loom_gate_world.quest_state.completed_quest_ids.append("quest.stabilize_outer_ring_barrier")
	loom_gate_world.quest_state.completed_quest_ids.append("quest.unlock_deep_ruin_entrance")
	var loom_gate_character := CharacterState.create_default()
	map.last_reported_region_id = loom_gate_world.current_region_id
	map.player.position = Vector2(2386, -96)
	map.update_region_presence(loom_gate_world, loom_gate_character)
	host._expect_equal(map.player.position.x, 2292.0, "locked phase well loom should push player before loom region")
	host._expect_equal(loom_gate_world.current_region_id, "region.phase_well_chamber", "locked phase well loom should keep chamber region")
	var unlocked_loom_world := WorldState.create_default()
	unlocked_loom_world.unlock_region("region.crystal_vein_field")
	unlocked_loom_world.unlock_region("region.pollution_edge")
	unlocked_loom_world.unlock_region("region.ruin_outer_ring")
	unlocked_loom_world.unlock_region("region.deep_ruin_threshold")
	unlocked_loom_world.unlock_region("region.inner_phase_well")
	unlocked_loom_world.unlock_region("region.phase_well_sink")
	unlocked_loom_world.unlock_region("region.phase_well_chamber")
	unlocked_loom_world.unlock_region("region.phase_well_loom")
	unlocked_loom_world.quest_state.completed_quest_ids.append("quest.stabilize_outer_ring_barrier")
	unlocked_loom_world.quest_state.completed_quest_ids.append("quest.unlock_deep_ruin_entrance")
	var unlocked_loom_character := CharacterState.create_default()
	map.last_reported_region_id = unlocked_loom_world.current_region_id
	map.player.position = Vector2(2386, -96)
	map.update_region_presence(unlocked_loom_world, unlocked_loom_character)
	host._expect_equal(unlocked_loom_world.current_region_id, "region.phase_well_loom", "unlocked phase well loom should update current region")
	map.player.free()
	map.free()


func _check_phase_well_frame_gate() -> void:
	var map := VerticalSliceMap.new()
	map.player = PlayerController.new()
	var frame_gate_world := WorldState.create_default()
	frame_gate_world.unlock_region("region.crystal_vein_field")
	frame_gate_world.unlock_region("region.pollution_edge")
	frame_gate_world.unlock_region("region.ruin_outer_ring")
	frame_gate_world.unlock_region("region.deep_ruin_threshold")
	frame_gate_world.unlock_region("region.inner_phase_well")
	frame_gate_world.unlock_region("region.phase_well_sink")
	frame_gate_world.unlock_region("region.phase_well_chamber")
	frame_gate_world.unlock_region("region.phase_well_loom")
	frame_gate_world.quest_state.completed_quest_ids.append("quest.stabilize_outer_ring_barrier")
	frame_gate_world.quest_state.completed_quest_ids.append("quest.unlock_deep_ruin_entrance")
	var frame_gate_character := CharacterState.create_default()
	map.last_reported_region_id = frame_gate_world.current_region_id
	map.player.position = Vector2(2666, -96)
	map.update_region_presence(frame_gate_world, frame_gate_character)
	host._expect_equal(map.player.position.x, 2572.0, "locked phase well frame should push player before frame region")
	host._expect_equal(frame_gate_world.current_region_id, "region.phase_well_loom", "locked phase well frame should keep loom region")
	var unlocked_frame_world := WorldState.create_default()
	unlocked_frame_world.unlock_region("region.crystal_vein_field")
	unlocked_frame_world.unlock_region("region.pollution_edge")
	unlocked_frame_world.unlock_region("region.ruin_outer_ring")
	unlocked_frame_world.unlock_region("region.deep_ruin_threshold")
	unlocked_frame_world.unlock_region("region.inner_phase_well")
	unlocked_frame_world.unlock_region("region.phase_well_sink")
	unlocked_frame_world.unlock_region("region.phase_well_chamber")
	unlocked_frame_world.unlock_region("region.phase_well_loom")
	unlocked_frame_world.unlock_region("region.phase_well_frame")
	unlocked_frame_world.quest_state.completed_quest_ids.append("quest.stabilize_outer_ring_barrier")
	unlocked_frame_world.quest_state.completed_quest_ids.append("quest.unlock_deep_ruin_entrance")
	var unlocked_frame_character := CharacterState.create_default()
	map.last_reported_region_id = unlocked_frame_world.current_region_id
	map.player.position = Vector2(2666, -96)
	map.update_region_presence(unlocked_frame_world, unlocked_frame_character)
	host._expect_equal(unlocked_frame_world.current_region_id, "region.phase_well_frame", "unlocked phase well frame should update current region")
	map.player.free()
	map.free()
