#!/usr/bin/env python3
import sys
from pathlib import Path


REQUIRED_TEXT_BY_FILE = {
    "docs/archive/features-demo-v1/demo-resource-chain-state-v1.md": [
        "Demo Resource Chain State V1",
        "资源 / 生产链",
        "状态序列化",
    ],
    "client/scripts/systems/demo_resource_chain_state_formatter.gd": [
        "class_name DemoResourceChainStateFormatter",
        "get_core_resource_ids",
        "format_hud_summary",
        "format_device_status_line",
        "format_result_feedback_line",
        "核心稳压缓冲包",
    ],
    "client/scripts/ui/hud_status_presenter.gd": [
        "DemoResourceChainStateFormatter.format_hud_summary",
    ],
    "client/scripts/ui/hud_device_panel_presenter.gd": [
        "DemoResourceChainStateFormatter.format_device_status_line",
    ],
    "client/scripts/systems/processing_system.gd": [
        "resource_chain",
        "show_resource_chain",
        "DemoResourceChainStateFormatter.format_result_feedback_line",
    ],
    "client/scripts/map/demo_crystal_resource_visual_layer.gd": [
        "class_name DemoCrystalResourceVisualLayer",
        "demo_default_path_asset_language_art_pass.gd",
        "demo_crystal_workface_asset_art_pass.gd",
        "get_workface_asset_count",
        "get_repositioned_output_label_count",
        "CRYSTAL_FOCUS_PICKUP_LABEL_ALPHA",
        "_position_output_pickup_label",
        "crystal.main_vein",
        "crystal.rich_vein",
        "crystal.current_mining_vein.subject",
        "crystal.current_output_tray.subject",
        "crystal.local_focus_marker_deemphasized",
        "flow.current_vein_to_output_tray.short_subject",
        "get_terrain_material_shape_count",
        "get_shaped_local_focus_marker_count",
        "terrain.crystal.harvest_face",
        "terrain.crystal.current_harvest_workface_subject",
        "terrain.crystal.current_workface_noise_cutout",
        "terrain.crystal.current_machine_deck_subject",
        "terrain.crystal.non_current_crystal_backdrop_muted",
        "terrain.crystal.legacy_planning_frame_deemphasized",
        "terrain.crystal.current_resource_foreground_anchors",
        "terrain.crystal.scrap_recovery_yard",
        "terrain.crystal.base_loading_mouth",
        "refresh_focus_visibility",
        "_deemphasize_legacy_crystal_blocks",
        "map_object.rich_crystal_vein",
    ],
    "client/scripts/map/demo_industrial_base_visual_layer.gd": [
        "class_name DemoIndustrialBaseVisualLayer",
        "refresh_pollution_chain_state",
        "operation_relation.reactor_to_storage",
        "operation_relation.storage_to_outfitting",
        "operation_relation.slurry_to_core_prep",
        "pollution_chain.residue_input_slot",
        "pollution_chain.filter_process_window",
        "pollution_chain.vial_output_slot",
        "pollution_chain.slurry_byproduct_slot",
        "pollution_chain.core_prep_route",
    ],
    "client/scripts/map/demo_first_industrial_path_visual_layer.gd": [
        "class_name DemoFirstIndustrialPathVisualLayer",
        "demo_default_path_asset_language_art_pass.gd",
        "STAGE_REACTOR_PROCESSING",
        "first_path.primary_player_lane",
        "first_path.base_receiving_bay",
        "first_path.reactor_work_window",
        "first_path.outfitting_handoff",
        "first_path.stage_feedback_lane",
        "first_path.stage.%s",
        "first_path.context_clarity_mask",
        "first_path.operation_relation.collector_to_receiving",
        "first_path.operation_relation.storage_to_outfitting",
        "first_path.single_signal_stage",
        "demo_first_industrial_path_handoff_art_pass.gd",
        "HandoffArtPass.draw_feedback",
        "CurrentObjectiveGuidanceLayer",
        "_set_context_layers_muted",
        "_has_first_path_output_context",
        "_quiet_global_planning_layers",
    ],
    "client/scripts/map/demo_first_industrial_path_handoff_art_pass.gd": [
        "class_name DemoFirstIndustrialPathHandoffArtPass",
        "BASE_HANDOFF_ASSET_BASIC_REACTOR",
        "first_path.assetized_base_handoff_device_group",
        "first_path.assetized_handoff_ports",
        "first_path.short_material_flow_segments",
        "first_path.assetized_feedback.outfitting_handoff.ready",
        "first_path.handoff_continuity.return_manifest_panel",
        "first_path.handoff_continuity.reactor_hopper_bridge",
        "first_path.handoff_continuity.storage_supply_manifest",
        "first_path.handoff_continuity.return_manifest.loaded",
        "first_path.handoff_continuity.reactor_hopper.processing",
        "first_path.handoff_continuity.outfitting_supply.latched",
        "draw_devices",
        "draw_ports",
        "draw_feedback",
    ],
    "client/scripts/map/demo_base_handoff_asset_art_pass.gd": [
        "class_name DemoBaseHandoffAssetArtPass",
        "res://assets/sprites/demo_first_screen/basic_reactor_module.svg",
        "res://assets/sprites/demo_first_screen/storage_crate_bank.svg",
        "res://assets/sprites/demo_first_screen/outfitting_station_rack.svg",
        "base_handoff_asset.old_route_suppression",
        "base_handoff_asset.reactor_asset",
        "base_handoff_asset.return_tray_subject",
        "base_handoff_asset.reactor_hopper_subject",
        "base_handoff_asset.storage_supply_subject",
        "base_handoff_asset.outfitting_latch_subject",
        "base_handoff_asset.short_stage_packets",
        "refresh_handoff_state",
        "draw_texture_rect",
    ],
    "client/scripts/map/demo_playable_scene_rebuild_layer.gd": [
        "class_name DemoPlayableSceneRebuildLayer",
        "Sprite2D.new",
        "playable_scene_compact_floor.svg",
        "playable_scene.terrain_floor",
        "playable_scene.outpost_core_machine",
        "playable_scene.basic_reactor_module",
        "playable_scene.crystal_ecology_cluster",
        "playable_scene.pollution_edge_pool",
        "playable_scene.first_objective_core_subject",
        "playable_scene.old_planning_layers_muted",
        "playable_scene.startup_presentation_suppressed",
        "playable_scene.compact_floor_not_fullscreen_overlay",
        "playable_scene.no_fullscreen_backdrop",
        "playable_scene.floor_islands_not_planning_grid",
        "playable_scene.floor_edges_matte_not_ui_frames",
        "playable_scene.far_core_station_excluded",
        "get_scene_sprite_node_count",
        "is_scene_active_at",
        "_set_context_layers_muted",
        "_set_context_rects_muted",
    ],
    "client/scripts/map/demo_base_first_screen_scene_layer.gd": [
        "class_name DemoBaseFirstScreenSceneLayer",
        "Polygon2D.new",
        "Sprite2D.new",
        "base_first_screen_rocky_ground.png",
        "base_first_screen_foundation_pads.png",
        "base_first_screen_pipe_network.png",
        "base_first_screen_cliff_edge.png",
        "base_first_screen_pollution_seep.png",
        "base_first_screen_outpost_core_machine.png",
        "base_first_screen_basic_reactor_module.png",
        "base_first_screen_storage_crate_bank.png",
        "base_first_screen_outfitting_station_rack.png",
        "base_first_screen_crystal_edge.png",
        "base_first_screen_scene.independent_scene_layer",
        "base_first_screen_scene.authored_scene_assets",
        "base_first_screen_scene.generated_scene_textures",
        "base_first_screen_scene.raster_sprite_pack",
        "base_first_screen_scene.outpost_region_scoped",
        "base_first_screen_scene.crystal_region_suppressed",
        "base_first_screen_scene.rocky_ground_material",
        "base_first_screen_scene.foundation_pad_asset",
        "base_first_screen_scene.cliff_edge_asset",
        "base_first_screen_scene.pipe_network_asset",
        "base_first_screen_scene.pollution_seep_asset",
        "base_first_screen_scene.pollution_edge_context",
        "base_first_screen_scene.solid_floor_mass",
        "base_first_screen_scene.platform_edge_boundaries",
        "base_first_screen_scene.low_profile_boundaries",
        "base_first_screen_scene.segmented_wall_edges",
        "base_first_screen_scene.outpost_core_volume",
        "base_first_screen_scene.reactor_volume",
        "base_first_screen_scene.storage_volume",
        "base_first_screen_scene.outfitting_volume",
        "base_first_screen_scene.device_silhouette_language",
        "base_first_screen_scene.right_crystal_edge_context",
        "base_first_screen_scene.right_crystal_edge_deemphasized",
        "base_first_screen_scene.old_rebuild_layer_deemphasized",
        "base_first_screen_scene.startup_stack_suppressed",
        "base_first_screen_scene.core_focus_compact",
        "base_first_screen_scene.existing_interactions_preserved",
        "ROLE_DEVICE",
        "SCENE_ASSET_MANIFEST",
        "SCENE_ASSET_LAYOUT",
        "DEVICE_VOLUME_IDS",
        "DEVICE_SILHOUETTE_IDS",
        "MATERIAL_BLOCK_IDS",
        "SERVICE_PORT_IDS",
        "CurrentObjectiveGuidanceLayer",
        "DemoPlayableSceneRebuildLayer",
        "DemoBaseStartupPresentationLayer",
        "get_scene_asset_count",
        "get_scene_sprite_node_count",
        "get_scene_asset_path",
        "get_device_volume_count",
        "get_device_silhouette_part_count",
        "get_material_block_count",
        "get_service_port_count",
        "_set_first_screen_focus_compact",
        "_set_context_layers_muted",
        "_set_context_rects_muted",
    ],
    "client/scripts/map/demo_default_path_asset_language_art_pass.gd": [
        "class_name DemoDefaultPathAssetLanguageArtPass",
        "draw_base_handoff_language",
        "draw_crystal_language",
        "draw_pollution_language",
        "draw_core_language",
        "default_path.asset_language.base.shared_service_floor",
        "terrain.crystal.assetized_ecology_sprite",
        "terrain.crystal.current_workface_clarity_plate",
        "terrain.pollution.assetized_pollution_pool",
        "station.assetized_write_device_machine",
    ],
    "client/scripts/map/demo_crystal_workface_asset_art_pass.gd": [
        "class_name DemoCrystalWorkfaceAssetArtPass",
        "res://assets/sprites/demo_crystal_workface/workface_floor.svg",
        "res://assets/sprites/demo_crystal_workface/current_crystal_vein.svg",
        "res://assets/sprites/demo_crystal_workface/crystal_collector_machine.svg",
        "res://assets/sprites/demo_crystal_workface/output_tray_loaded.svg",
        "crystal_workface_asset.current_vein",
        "harvestable_resource",
        "collector_device",
        "pickup_output",
        "draw_workface",
        "draw_texture_rect",
        "crystal.workface.asset.current_vein_sprite",
        "crystal.workface.asset.enlarged_output_tray_subject",
        "flow.crystal_workface.asset.short_material_packets",
        "flow.crystal_workface.asset.pickup_ready_signal",
        "terrain.crystal.workface.asset.floor_sprite",
        "terrain.crystal.workface.asset.expanded_linework_suppression",
        "terrain.crystal.workface.asset.forward_pickup_tray",
        "terrain.crystal.workface.asset.sprite_manifest",
    ],
    "client/scenes/maps/VerticalSliceMap.tscn": [
        "DemoCrystalResourceVisualLayer",
        "demo_crystal_resource_visual_layer.gd",
        "DemoFirstIndustrialPathVisualLayer",
        "demo_first_industrial_path_visual_layer.gd",
        "DemoBaseHandoffAssetArtPass",
        "demo_base_handoff_asset_art_pass.gd",
        "DemoPlayableSceneRebuildLayer",
        "demo_playable_scene_rebuild_layer.gd",
        "DemoBaseFirstScreenSceneLayer",
        "demo_base_first_screen_scene_layer.gd",
    ],
    "client/scripts/game/game_root.gd": [
        "DemoBaseFirstScreenSceneLayer",
        "refresh_scene_state(world_state, character_state)",
    ],
    "client/scripts/ui/hud_log_presenter.gd": [
        '"资源链"',
        "resource_chain",
    ],
    "client/scripts/checks/demo_resource_chain_state_check.gd": [
        "Demo resource chain state checks passed.",
        "_check_core_resource_scope",
        "_check_hud_resource_chain_state",
        "_check_device_panel_resource_chain_state",
        "_check_processing_result_resource_chain",
        "_check_playable_scene_rebuild_layer",
        "_check_crystal_resource_visual_layer",
        "playable scene rebuild layer builds sprite nodes instead of debug rectangles",
        "playable scene rebuild layer uses a compact floor sprite instead of the old fullscreen platform overlay",
        "playable scene rebuild layer makes the damaged outpost core the subject",
        "playable scene rebuild layer suppresses old color-block planning context",
        "playable scene rebuild layer hides the old startup presentation stack in the same first screen",
        "playable scene rebuild layer removes the fullscreen backdrop board",
        "playable scene rebuild layer uses floor islands instead of a planning grid",
        "playable scene rebuild layer keeps floor edges matte instead of UI-framed",
        "playable scene rebuild layer does not cover the far core station",
        "_check_base_first_screen_scene_layer",
        "base first screen scene layer exists",
        "base first screen scene uses authored assets instead of a full concept image",
        "base first screen scene uses generated scene textures instead of a screenshot",
        "base first screen scene uses raster sprites as the main visual medium",
        "base first screen scene is scoped to the outpost region",
        "base first screen scene suppresses itself in crystal region context",
        "base first screen scene reads as rocky alien ground",
        "base first screen scene gives devices generated foundation pads",
        "base first screen scene uses a generated cliff edge asset",
        "base first screen scene includes a pipe network asset",
        "base first screen scene includes a generated pollution seep asset",
        "base first screen scene includes pollution edge context",
        "base first screen scene registers visual scene assets",
        "base first screen scene instantiates visual scene sprites",
        "base first screen scene has a generated rocky ground asset",
        "base first screen rocky ground raster path is registered",
        "base first screen foundation pads use raster art",
        "base first screen pipe network uses raster art",
        "base first screen scene uses solid floor mass",
        "base first screen scene keeps boundaries low profile",
        "base first screen scene breaks wall edges into short segments",
        "base first screen scene gives the core a solid volume",
        "base first screen scene adds device-specific silhouette language",
        "base first screen scene keeps crystal context to the right edge",
        "base first screen scene keeps right crystal edge secondary",
        "base first screen scene lowers the current objective overlay",
        "base first screen hides the core scene label near the player",
        "base first screen scene hides the old playable rebuild stack in its first-screen scope",
        "base first screen scene disables itself after entering the crystal region",
        "base first screen scene does not cover the crystal workface",
        "base first screen keeps the default first interaction on the outpost core",
        "first industrial path layer registers the playable path slice",
        "_check_first_industrial_path_stage_changes",
        "_check_operation_relation_visual_shapes",
        "first path links collector output to receiving",
        "first path gives the base handoff segment assetized devices",
        "base handoff visual checkpoint marks outfitting handoff feedback",
        "first industrial path layer registers returned material manifest feedback",
        "first industrial path layer keeps the hopper bridge active during processing",
        "base handoff visual checkpoint latches storage output into outfitting",
        "base handoff asset layer suppresses old route linework",
        "base handoff asset layer gives returned materials a tray subject",
        "base handoff asset layer marks reactor processing feedback",
        "base handoff asset checkpoint locks the outfitting receipt subject",
        "first_path.stage.reactor_processing",
        "default_path.asset_language.base.shared_service_floor",
        "terrain.crystal.assetized_ecology_sprite",
        "terrain.crystal.current_workface_clarity_plate",
        "crystal visual layer makes the current vein the foreground subject",
        "flow.current_vein_to_output_tray.short_subject",
        "terrain.crystal.legacy_planning_frame_deemphasized",
        "STAGE_OUTFITTING_READY",
        "starting supplies from skipping field pickup",
        "restores background layers outside its scope",
        "crystal visual layer stays hidden at startup objective",
        "crystal visual layer registers mining terrain materials",
        "terrain.crystal.return_cart_lane",
        "crystal visual layer keeps local interactable markers tightly scoped",
        "crystal visual layer keeps local focus ring from becoming the subject",
        "terrain.crystal.current_machine_deck_subject",
        "crystal workface registers dedicated sprite assets",
        "crystal workface has an assetized current vein sprite",
        "crystal workface has an assetized collector machine sprite",
        "crystal workface has an assetized loaded output tray sprite",
        "crystal visual layer draws the current vein as a sprite subject",
        "crystal visual layer repositions the output tray label away from the device body",
        "crystal output tray label sits below the pickup tray",
        "crystal output tray label is a secondary confirmation cue",
        "crystal visual layer enlarges the output tray as the pickup subject",
        "flow.crystal_workface.asset.short_material_packets",
        "flow.crystal_workface.asset.pickup_ready_signal",
        "terrain.crystal.workface.asset.floor_sprite",
        "terrain.crystal.workface.asset.expanded_linework_suppression",
        "terrain.crystal.workface.asset.forward_pickup_tray",
        "_check_pollution_chain_hud_and_visual_state",
        "pollution_chain.core_prep_route.ready",
        "_check_resource_chain_state_roundtrip",
    ],
    "scripts/check-client.sh": [
        "check-client-demo-resource-chain-state.py",
        "demo_resource_chain_state_check.gd",
    ],
    "scripts/check-client-flow.ps1": [
        "demo_resource_chain_state_check.gd",
    ],
}


def main() -> int:
    repo_root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parents[1]
    errors: list[str] = []

    for relative_path, required_texts in REQUIRED_TEXT_BY_FILE.items():
        path = repo_root / relative_path
        if not path.is_file():
            errors.append(f"{relative_path}: missing file")
            continue
        content = path.read_text(encoding="utf-8")
        for required_text in required_texts:
            if required_text not in content:
                errors.append(f"{relative_path}: missing demo resource chain state text '{required_text}'")

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    print("Client demo resource chain state checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
