extends "res://production/verify-window.gd"

## Bounded supplement: real mouse destinations and held keys, no actor teleportation.
func run(app: Control) -> void:
	verification_scope = "Independent Production entry; mouse destinations and held-key movement/collision; focus lifecycle signals; visible confirmation button pressed signals; no actor/production state injection"
	prepare(app, 90)
	await _foreground()
	await _settle(20)
	await _key(KEY_2)
	await _world_click(Vector2i(-1, -2))
	_expect(world.model.kits.reactor == 0, "number shortcut and mouse place the reactor")
	if not failures.is_empty():
		await _shot("navigation-placement-failed")
		_finish()
		return
	await _click(world.hud.buttons.close_inspector)
	await _click(world.hud.buttons.build)
	await _click(world.hud.buttons.zoom_in)
	await _click(world.hud.buttons.zoom_in)
	await _world_click(Vector2i(-3, -6))
	await _until(func(): return Vector2(world.actor.x, world.actor.z).distance_to(Vector2(-2.5, -5.5)) < 0.15, 5, "ground-click walks around reactor side")
	await _world_click(Vector2i(-1, -6))
	await _until(func(): return Vector2(world.actor.x, world.actor.z).distance_to(Vector2(-0.5, -5.5)) < 0.15, 3, "ground-click reaches behind reactor")
	await _key(KEY_S, true)
	await _seconds(1.35)
	await _key(KEY_S, false)
	_expect(world.actor.z < -2.28 and world.actor.z > -2.5, "held movement collides with actual reactor footprint")
	_observe("behind_collision")
	await _shot("11-character-behind-reactor")
	await _key(KEY_S, true)
	await _key(KEY_D, true)
	await _seconds(1)
	await _key(KEY_S, false)
	await _key(KEY_D, false)
	await _world_click(Vector2i(0, 4))
	await _until(func(): return Vector2(world.actor.x, world.actor.z).distance_to(Vector2(0.5, 4.5)) < 0.15, 5, "engineer moves around edge and reaches front")
	await _shot("12-character-front-reactor")
	await _click(world.hud.buttons.build)
	await _click(world.hud.buttons.storage)
	await _world_click(Vector2i(0, 4))
	_expect(world.model.kits.storage == 1 and world.model.entity_at(Vector2i(0, 4)).is_empty(), "placing over engineer fails without spending kit")
	await _key(KEY_ESCAPE)
	await _click(world.hud.buttons.pause)
	var time_before: float = world.model.time
	await _seconds(0.3)
	_expect(is_equal_approx(world.model.time, time_before), "pause button stops authoritative clock")
	await _click(world.hud.buttons.pause)
	await _choose("belt")
	await _start_drag(Vector2i(3, 4))
	await _drag_to(Vector2i(5, 4))
	# This supplements the actual macOS focus-pause observation from full runs.
	# Signal injection is explicitly limited to the input-lifecycle branch here.
	get_window().focus_exited.emit()
	await get_tree().process_frame
	_expect(world.ui.stroke.is_empty() and not world.pointer and world.model.kits.belt == 24, "focus-exit signal cancels drag without kits")
	time_before = world.model.time
	await _seconds(0.3)
	_expect(is_equal_approx(world.model.time, time_before), "focus-exit signal pauses production")
	get_window().focus_entered.emit()
	await _mouse_up(_cell_screen(Vector2i(5, 4)))
	await _click(world.hud.buttons.restart)
	_expect(world.hud.restart.visible, "restart requires visible confirmation")
	world.hud.restart.get_cancel_button().pressed.emit()
	await _settle()
	_expect(not world.hud.restart.visible, "cancel button closes confirmation")
	_expect(world.model.entities.size() == 1, "cancel restart preserves the placed reactor")
	await _click(world.hud.buttons.restart)
	world.hud.restart.get_ok_button().pressed.emit()
	await _settle()
	_expect(not world.hud.restart.visible, "confirm button closes confirmation")
	_expect(world.model.entities.is_empty() and world.model.kits.reactor == 1 and world.model.kits.belt == 24, "confirmed restart returns to empty yard")
	await _shot("13-reset-empty-yard")
	_finish()
